// <auto-generated />
using System;
using ElectricalEngineerTools.DAL.ContextDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ElectricalEngineerTools.DAL.Migrations
{
    [DbContext(typeof(ElectricsContext))]
    [Migration("20210117115740_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ElectricalEngineerTools.DAL.Entities.LightingFixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClimaticModification")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DiffuserMaterial")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IP")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsFireproof")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Power")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("LightingFixtures");
                });
#pragma warning restore 612, 618
        }
    }
}
